### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [VSRonin/QtModelUtilities#31]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “AbstractModelSerialiser”](https://github.com/VSRonin/QtModelUtilities/blob/38901e1e306bb01e52c4f474da58c90f08675693/src/abstractmodelserialiser.cpp#L190 "Update candidate: Destructor for AbstractModelSerialiser").

**Comment by VSRonin** [comment]
Fixed switching to QScopedPointer
