### ISSUE TITLE
Conversion of a standard item model into a SQL model

### ISSUE THREAD

**Issue by elfring** [VSRonin/QtModelUtilities#32]
[The class “QSqlTableModel”](https://doc.qt.io/qt-5/qsqltablemodel.html#details "Description for QSqlTableModel") is available. This programming interface requires the specification of a database.
:crystal_ball: How are the chances to treat objects which were based on [the class “QStandardItemModel”](https://doc.qt.io/qt-5/qstandarditemmodel.html#details "Description for QStandardItemModel") as [a kind of in-memory database](https://en.wikipedia.org/wiki/In-memory_database "Description for the usage of in-memory databases")?

**Comment by VSRonin** [comment]
That would require a plugin to implement a QSqlDriver that acts on models. Doable but pretty hard to implement
