### ISSUE TITLE
persistent model indexes corrupted

### ISSUE THREAD

**Issue by Joey5460** [VSRonin/QtModelUtilities#38]
When I set tableview->hideColumn(0), enable setSortingEnable(true), input something in a * row then trigger sorting by clicking tableview header, the "persistent model indexes corrupted " happened.

**Comment by Joey5460** [comment]
I am not sure about it now. it did not happen again.

**Comment by VSRonin** [comment]
probably black magic. I did solve some bugs in the dev branch though so I suggest cloning that one rather than the master. I didn't complete the documentation so I didn't merge them yet

**Comment by Joey5460** [comment]
Thank you for your effort. I have put your work in project. Let's make it perfect.
