### ISSUE TITLE
RootIndexProxyModel calls endResetModel too early after root row or root column is deleted

### ISSUE THREAD

**Issue by vserdyuk** [VSRonin/QtModelUtilities#60]
When root row or root column is removed, RootIndexProxyModel calls endResetModel before source model is done modifying its data.
Now it does the following:
`SourceModel::beginRemoveRows() -> RootIndexProxyModelPrivate::checkRootRowRemoved -> RootIndexProxyModel::setRootIndex -> RootIndexProxyModel::beginResetModel() -> RootIndexProxyModel::**endResetModel**() -> view is updated, other slots are called -> only then source model actually modifies the data -> SourceModel::endRemoveRows() -> and RootIndexProxyModel emits nothing, view is not updated.`

The order should be:
`SourceModel::beginRemoveRows() -> RootIndexProxyModelPrivate::checkRootRowRemoved -> m_rootRowDeleted = true -> RootIndexProxyModel::beginResetModel() -> other slots are called -> source model actually modifies the data -> SourceModel::endRemoveRows() -> RootIndexProxyModel::endResetModel() after source model updated its data -> view is updated correctly.`

I rebased my patch on recent changes, please, take a look: [003-fix-rootindexproxymodel-rootrowremoved-rebased.patch](https://github.com/VSRonin/QtModelUtilities/files/14615342/003-fix-rootindexproxymodel-rootrowremoved-rebased.patch)

**Comment by VSRonin** [comment]
Thanks for flagging and even providing the solution
